//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThoiTrangKD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public string MaLLV { get; set; }
        public Nullable<System.DateTime> Ngaylamviec { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> Tongcalamviec { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
