//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThoiTrangKD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDon = new HashSet<HoaDon>();
            this.LichLamViec = new HashSet<LichLamViec>();
            this.Luong = new HashSet<Luong>();
        }
    
        public string MaNV { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string Gioitinh { get; set; }
        public string HovaTen { get; set; }
        public Nullable<double> Luongtheogio { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string SDT { get; set; }
        public int MaTK { get; set; }
        public string Chucvu { get; set; }
        public Nullable<double> Phucap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichLamViec> LichLamViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luong> Luong { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
